<?php
    require_once("assets/inc/header.inc.php");
?>
    <main>
    <?php
        require_once("assets/inc/alignmentQuiz.inc.php");
        ?>
    </main>
<?php
    require_once("assets/inc/footer.inc.php");
?>
