<?php
    require_once("Assets/inc/header.inc.php");
?>
    <main>
        <?php
            require_once("Assets/inc/contactForm.inc.php");
        ?>
    </main>
<?php
    require_once("Assets/inc/footer.inc.php");
?>
