<?php
    require_once("./Assets/inc/header.inc.php");
?>
    <main>
    <?php
        require_once("Assets/inc/contrastQuiz.inc.php");
    ?>
    </main>
<?php
    require_once("Assets/inc/footer.inc.php");
?>
